### PR TITLE
[SAR-65] Added support for path variables with regexp

### LINKED ISSUE #71: @PathVariable issue
Hi, I'm trying to use the path variable feature like this, but it throws

`net.kaczmarzyk.spring.data.jpa.web.InvalidPathVariableRequestedException: Requested path variable {parentId} is not present in Controller request mapping annotations`

What I'm trying
`    @RequestMapping(method = RequestMethod.GET, path = "/{parentId}/translations/{translationId}/meta/search")
    public ResponseEntity<List<MetaDetailResponseDto>> search(
            @Conjunction(value = {
                    @Or(value = @Spec(path = "metaType", params = {"meta_type"}, spec = Equal.class))
            }, and = @Spec(path = "entity_id", pathVars = "parentId", spec = Equal.class)) Specification<MetaDetail> specification) {
        return ResponseEntity.status(HttpStatus.OK).body(this.adminDestinationTranslationMetaDetailService.search(specification));
    }`

it is an issue or am I doing anything wrong?

Kind Regards,
Sithira

### PR DESCRIPTION
**Pull request by jradlica**
Related to issues: #65 

It's possible that these changes will also fix #71

### CODE REVIEW

File: src/test/java/net/kaczmarzyk/spring/data/jpa/utils/PathVariableResolverTest.java [hunk 1]
```diff
@@ -19,46 +19,56 @@
...
-				.forPathPatternAndActualPath("/customers/{customerId}/orders", "/customers/77/orders");
+		Map<String, String> resolvedVariables = PathVariableResolver
+				.resolvePathVariables("/customers/{customerId}/orders", "/customers/77/orders");
 
-		assertThat(resolver.resolveValue("customerId")).isEqualTo("77");
+		assertThat(resolvedVariables.get("customerId")).isEqualTo("77");
 	}
 
 	@Test
 	public void extractsPathVariableAmongMultiplePathVariables() {
```
Comment (tkaczmarzyk) [inline src/test/java/net/kaczmarzyk/spring/data/jpa/utils/PathVariableResolverTest.java:51]: I think we need to explicitly test scenario when url does not match the pattern e.g.

/customers/{id:[0-9]}
vs
/customers/notANumber

File: src/test/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestProcessingContextPathVariableResolverTest.java [hunk 2]
```diff
@@ -0,0 +1,346 @@
...
+				testMethodParameter("testMethodUsingPathVariableWithRegexp_getMapping_path", testController), req);
+
+		assertThat(context.getPathVariableValue("customerId")).isEqualTo("888");
+		assertThat(context.getPathVariableValue("orderId")).isEqualTo("99");
+	}
+
+	@RequestMapping("/customers/{customerId}")
+	public static class TestControllerWithClassLevelRequestMappingWithValue {
+
+		@RequestMapping
```
Comment (tkaczmarzyk) [inline src/test/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestProcessingContextPathVariableResolverTest.java:162]: formatting

File: src/test/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestProcessingContextPathVariableResolverTest.java [hunk 3]
```diff
@@ -0,0 +1,346 @@
...
+        public void testMethodUsingPathVariable_requestMapping_empty(Specification<Object> spec) {
+        }
+		
+		@GetMapping
```
Comment (tkaczmarzyk) [inline src/test/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestProcessingContextPathVariableResolverTest.java:166]: formatting

File: src/test/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestProcessingContextPathVariableResolverTest.java [hunk 4]
```diff
@@ -0,0 +1,346 @@
...
+        public void testMethodUsingPathVariable_getMapping_empty(Specification<Object> spec) {
+        }
+		
+		@RequestMapping(path = "/orders/{orderId}")
```
Comment (tkaczmarzyk) [inline src/test/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestProcessingContextPathVariableResolverTest.java:170]: formatting

File: src/test/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestProcessingContextPathVariableResolverTest.java [hunk 5]
```diff
@@ -0,0 +1,346 @@
...
+    	
+    	@RequestMapping(value = "/orders/{orderId}")
+        public void testMethodUsingPathVariable_requestMapping_value(Specification<Object> spec) {
+        }
+
+		@RequestMapping(value = "/orders/{orderId:.*}")
+		public void testMethodUsingPathVariableWithRegexp_requestMapping_value(Specification<Object> spec) {
+		}
+
+    	@GetMapping(path = "/orders/{orderId}")
```
Comment (tkaczmarzyk) [inline src/test/java/net/kaczmarzyk/spring/data/jpa/web/WebRequestProcessingContextPathVariableResolverTest.java:186]: formatting -- please revisit the whole file
